#!/bin/bash

if [ $SUDO_UID ]; then
    NAME=applepi.desktop
    DESKTOP=/home/$SUDO_USER/Desktop
    PATH=$DESKTOP/$NAME
    /usr/bin/xdg-desktop-menu  uninstall $NAME
    if [ -f $PATH ]; then
        /usr/bin/rm $PATH
    fi
fi

exit 0

