

const char *xpm_80ColCharsMono[] =
{
    "8 4096 2 1 0 0",
    "- c black m black s black_color",
    "X c green m green s light_color",

    "X---XXXX",    // 00
    "X---XXXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-X-X-XXX",
    "-X-X-XXX",
    "-X---XXX",
    "-X---XXX",
    "-X--XXXX",
    "-X--XXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "X----XXX",
    "X----XXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XX-XXXXX",    // 01
    "XX-XXXXX",
    "X-X-XXXX",
    "X-X-XXXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-----XXX",
    "-----XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "----XXXX",    // 02
    "----XXXX",
    "X-XX-XXX",
    "X-XX-XXX",
    "X-XX-XXX",
    "X-XX-XXX",
    "X---XXXX",
    "X---XXXX",
    "X-XX-XXX",
    "X-XX-XXX",
    "X-XX-XXX",
    "X-XX-XXX",
    "----XXXX",
    "----XXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X---XXXX",    // 03
    "X---XXXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "X---XXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "----XXXX",    // 04
    "----XXXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "----XXXX",
    "----XXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-----XXX",    // 05
    "-----XXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "----XXXX",
    "----XXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-----XXX",
    "-----XXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-----XXX",    // 06
    "-----XXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "----XXXX",
    "----XXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X----XXX",    // 07
    "X----XXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XX--XXX",
    "-XX--XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "X----XXX",
    "X----XXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-XXX-XXX",    // 08
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-----XXX",
    "-----XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X---XXXX",    // 09
    "X---XXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "X---XXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXXX-XXX",    // 0A
    "XXXX-XXX",
    "XXXX-XXX",
    "XXXX-XXX",
    "XXXX-XXX",
    "XXXX-XXX",
    "XXXX-XXX",
    "XXXX-XXX",
    "XXXX-XXX",
    "XXXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "X---XXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-XXX-XXX",    // 0B
    "-XXX-XXX",
    "-XX-XXXX",
    "-XX-XXXX",
    "-X-XXXXX",
    "-X-XXXXX",
    "--XXXXXX",
    "--XXXXXX",
    "-X-XXXXX",
    "-X-XXXXX",
    "-XX-XXXX",
    "-XX-XXXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-XXXXXXX",    // 0C
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-----XXX",
    "-----XXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-XXX-XXX",    // 0D
    "-XXX-XXX",
    "--X--XXX",
    "--X--XXX",
    "-X-X-XXX",
    "-X-X-XXX",
    "-X-X-XXX",
    "-X-X-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-XXX-XXX",    // 0E
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "--XX-XXX",
    "--XX-XXX",
    "-X-X-XXX",
    "-X-X-XXX",
    "-XX--XXX",
    "-XX--XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X---XXXX",    // 0F
    "X---XXXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "X---XXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "----XXXX",    // 10
    "----XXXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "----XXXX",
    "----XXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X---XXXX",    // 11
    "X---XXXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-X-X-XXX",
    "-X-X-XXX",
    "-XX-XXXX",
    "-XX-XXXX",
    "X--X-XXX",
    "X--X-XXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "----XXXX",    // 12
    "----XXXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "----XXXX",
    "----XXXX",
    "-X-XXXXX",
    "-X-XXXXX",
    "-XX-XXXX",
    "-XX-XXXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X---XXXX",    // 13
    "X---XXXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "X---XXXX",
    "X---XXXX",
    "XXXX-XXX",
    "XXXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "X---XXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-----XXX",    // 14
    "-----XXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-XXX-XXX",    // 15
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "X---XXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-XXX-XXX",    // 16
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "X-X-XXXX",
    "X-X-XXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-XXX-XXX",    // 17
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-X-X-XXX",
    "-X-X-XXX",
    "-X-X-XXX",
    "-X-X-XXX",
    "--X--XXX",
    "--X--XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-XXX-XXX",    // 18
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "X-X-XXXX",
    "X-X-XXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "X-X-XXXX",
    "X-X-XXXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-XXX-XXX",    // 19
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "X-X-XXXX",
    "X-X-XXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-----XXX",    // 1A
    "-----XXX",
    "XXXX-XXX",
    "XXXX-XXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "X-XXXXXX",
    "X-XXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-----XXX",
    "-----XXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-----XXX",    // 1B
    "-----XXX",
    "--XXXXXX",
    "--XXXXXX",
    "--XXXXXX",
    "--XXXXXX",
    "--XXXXXX",
    "--XXXXXX",
    "--XXXXXX",
    "--XXXXXX",
    "--XXXXXX",
    "--XXXXXX",
    "-----XXX",
    "-----XXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXXXXXXX",    // 1C
    "XXXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "X-XXXXXX",
    "X-XXXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XXXX-XXX",
    "XXXX-XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-----XXX",    // 1D
    "-----XXX",
    "XXX--XXX",
    "XXX--XXX",
    "XXX--XXX",
    "XXX--XXX",
    "XXX--XXX",
    "XXX--XXX",
    "XXX--XXX",
    "XXX--XXX",
    "XXX--XXX",
    "XXX--XXX",
    "-----XXX",
    "-----XXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXXXXXXX",    // 1E
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "X---XXXX",
    "X---XXXX",
    "-X-X-XXX",
    "-X-X-XXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",


    "XXXXXXXX",    // 1F
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "-----XXX",
    "-----XXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXXXXXXX",    // 20
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXX-XXXX",    // 21
    "XXX-XXXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XX-X-XXX",    // 22
    "XX-X-XXX",
    "XX-X-XXX",
    "XX-X-XXX",
    "XX-X-XXX",
    "XX-X-XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X-X-XXXX",    // 23
    "X-X-XXXX",
    "X-X-XXXX",
    "X-X-XXXX",
    "-----XXX",
    "-----XXX",
    "X-X-XXXX",
    "X-X-XXXX",
    "-----XXX",
    "-----XXX",
    "X-X-XXXX",
    "X-X-XXXX",
    "X-X-XXXX",
    "X-X-XXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XX-XXXXX",    // 24
    "XX-XXXXX",
    "X----XXX",
    "X----XXX",
    "-X-XXXXX",
    "-X-XXXXX",
    "X---XXXX",
    "X---XXXX",
    "XX-X-XXX",
    "XX-X-XXX",
    "----XXXX",
    "----XXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "--XXXXXX",    // 25
    "--XXXXXX",
    "--XX-XXX",
    "--XX-XXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "X-XXXXXX",
    "X-XXXXXX",
    "-XX--XXX",
    "-XX--XXX",
    "XXX--XXX",
    "XXX--XXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X-XXXXXX",    // 26
    "X-XXXXXX",
    "-X-XXXXX",
    "-X-XXXXX",
    "-X-XXXXX",
    "-X-XXXXX",
    "X-XXXXXX",
    "X-XXXXXX",
    "-X-X-XXX",
    "-X-X-XXX",
    "-XX-XXXX",
    "-XX-XXXX",
    "X--X-XXX",
    "X--X-XXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXX-XXXX",    // 27
    "XXX-XXXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XX-XXXXX",    // 28
    "XX-XXXXX",
    "X-XXXXXX",
    "X-XXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "X-XXXXXX",
    "X-XXXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XX-XXXXX",    // 29
    "XX-XXXXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XXXX-XXX",
    "XXXX-XXX",
    "XXXX-XXX",
    "XXXX-XXX",
    "XXXX-XXX",
    "XXXX-XXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XX-XXXXX",    // 2A
    "XX-XXXXX",
    "-X-X-XXX",
    "-X-X-XXX",
    "X---XXXX",
    "X---XXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "X---XXXX",
    "X---XXXX",
    "-X-X-XXX",
    "-X-X-XXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXXXXXXX",    // 2B
    "XXXXXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "-----XXX",
    "-----XXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXXXXXXX",    // 2C
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXXXXXXX",    // 2D
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "X-----XX",
    "X-----XX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXXXXXXX",    // 2E
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXXXXXXX",    // 2F
    "XXXXXXXX",
    "XXXX-XXX",
    "XXXX-XXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "X-XXXXXX",
    "X-XXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X---XXXX",    // 30
    "X---XXXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XX--XXX",
    "-XX--XXX",
    "-X-X-XXX",
    "-X-X-XXX",
    "--XX-XXX",
    "--XX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "X---XXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XX-XXXXX",    // 31
    "XX-XXXXX",
    "X--XXXXX",
    "X--XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "X---XXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X---XXXX",    // 32
    "X---XXXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "XXXX-XXX",
    "XXXX-XXX",
    "XX--XXXX",
    "XX--XXXX",
    "X-XXXXXX",
    "X-XXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "-----XXX",
    "-----XXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-----XXX",    // 33
    "-----XXX",
    "XXXX-XXX",
    "XXXX-XXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XX--XXXX",
    "XX--XXXX",
    "XXXX-XXX",
    "XXXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "X---XXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXX-XXXX",    // 34
    "XXX-XXXX",
    "XX--XXXX",
    "XX--XXXX",
    "X-X-XXXX",
    "X-X-XXXX",
    "-XX-XXXX",
    "-XX-XXXX",
    "-----XXX",
    "-----XXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-----XXX",    // 35
    "-----XXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "----XXXX",
    "----XXXX",
    "XXXX-XXX",
    "XXXX-XXX",
    "XXXX-XXX",
    "XXXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "X---XXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XX---XXX",    // 36
    "XX---XXX",
    "X-XXXXXX",
    "X-XXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "----XXXX",
    "----XXXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "X---XXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-----XXX",    // 37
    "-----XXX",
    "XXXX-XXX",
    "XXXX-XXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "X-XXXXXX",
    "X-XXXXXX",
    "X-XXXXXX",
    "X-XXXXXX",
    "X-XXXXXX",
    "X-XXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X---XXXX",    // 38
    "X---XXXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "X---XXXX",
    "X---XXXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "X---XXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X---XXXX",    // 39
    "X---XXXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "X----XXX",
    "X----XXX",
    "XXXX-XXX",
    "XXXX-XXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "---XXXXX",
    "---XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXXXXXXX",    // 3A
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXXXXXXX",    // 3B
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXX-XXXX",    // 3C
    "XXX-XXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "X-XXXXXX",
    "X-XXXXXX",
    "-XXXXXXX",
    "-XXXXXXX",
    "X-XXXXXX",
    "X-XXXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXXXXXXX",    // 3D
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "-----XXX",
    "-----XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "-----XXX",
    "-----XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XX-XXXXX",    // 3E
    "XX-XXXXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XXXX-XXX",
    "XXXX-XXX",
    "XXXXX-XX",
    "XXXXX-XX",
    "XXXX-XXX",
    "XXXX-XXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X---XXXX",    // 3F
    "X---XXXX",
    "-XXX-XXX",
    "-XXX-XXX",
    "XXX-XXXX",
    "XXX-XXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-XXX----",    // 40
    "-XXX----",
    "X---X---",
    "X---X---",
    "X-X-X---",
    "X-X-X---",
    "X-XXX---",
    "X-XXX---",
    "X-XX----",
    "X-XX----",
    "X-------",
    "X-------",
    "-XXXX---",
    "-XXXX---",
    "--------",
    "--------",


    "--X-----",    // 41
    "--X-----",
    "-X-X----",
    "-X-X----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "XXXXX---",
    "XXXXX---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "XXXX----",    // 42
    "XXXX----",
    "-X--X---",
    "-X--X---",
    "-X--X---",
    "-X--X---",
    "-XXX----",
    "-XXX----",
    "-X--X---",
    "-X--X---",
    "-X--X---",
    "-X--X---",
    "XXXX----",
    "XXXX----",
    "--------",
    "--------",


    "-XXX----",    // 43
    "-XXX----",
    "X---X---",
    "X---X---",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X---X---",
    "X---X---",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "XXXX----",    // 44
    "XXXX----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "XXXX----",
    "XXXX----",
    "--------",
    "--------",


    "XXXXX---",    // 45
    "XXXXX---",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "XXXX----",
    "XXXX----",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "XXXXX---",
    "XXXXX---",
    "--------",
    "--------",


    "XXXXX---",    // 46
    "XXXXX---",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "XXXX----",
    "XXXX----",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "--------",
    "--------",


    "-XXXX---",    // 47
    "-XXXX---",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X--XX---",
    "X--XX---",
    "X---X---",
    "X---X---",
    "-XXXX---",
    "-XXXX---",
    "--------",
    "--------",


    "X---X---",    // 48
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "XXXXX---",
    "XXXXX---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "-XXX----",    // 49
    "-XXX----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "----X---",    // 4A
    "----X---",
    "----X---",
    "----X---",
    "----X---",
    "----X---",
    "----X---",
    "----X---",
    "----X---",
    "----X---",
    "X---X---",
    "X---X---",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "X---X---",    // 4B
    "X---X---",
    "X--X----",
    "X--X----",
    "X-X-----",
    "X-X-----",
    "XX------",
    "XX------",
    "X-X-----",
    "X-X-----",
    "X--X----",
    "X--X----",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "X-------",    // 4C
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "XXXXX---",
    "XXXXX---",
    "--------",
    "--------",


    "X---X---",    // 4D
    "X---X---",
    "XX-XX---",
    "XX-XX---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "X---X---",    // 4E
    "X---X---",
    "X---X---",
    "X---X---",
    "XX--X---",
    "XX--X---",
    "X-X-X---",
    "X-X-X---",
    "X--XX---",
    "X--XX---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "-XXX----",    // 4F
    "-XXX----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "XXXX----",    // 50
    "XXXX----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "XXXX----",
    "XXXX----",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "--------",
    "--------",


    "-XXX----",    // 51
    "-XXX----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X-X-X---",
    "X-X-X---",
    "X--X----",
    "X--X----",
    "-XX-X---",
    "-XX-X---",
    "--------",
    "--------",


    "XXXX----",    // 52
    "XXXX----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "XXXX----",
    "XXXX----",
    "X-X-----",
    "X-X-----",
    "X--X----",
    "X--X----",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "-XXX----",    // 53
    "-XXX----",
    "X---X---",
    "X---X---",
    "X-------",
    "X-------",
    "-XXX----",
    "-XXX----",
    "----X---",
    "----X---",
    "X---X---",
    "X---X---",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "XXXXX---",    // 54
    "XXXXX---",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--------",
    "--------",


    "X---X---",    // 55
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "X---X---",    // 56
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "-X-X----",
    "-X-X----",
    "--X-----",
    "--X-----",
    "--------",
    "--------",


    "X---X---",    // 57
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "XX-XX---",
    "XX-XX---",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "X---X---",    // 58
    "X---X---",
    "X---X---",
    "X---X---",
    "-X-X----",
    "-X-X----",
    "--X-----",
    "--X-----",
    "-X-X----",
    "-X-X----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "X---X---",    // 59
    "X---X---",
    "X---X---",
    "X---X---",
    "-X-X----",
    "-X-X----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--------",
    "--------",


    "XXXXX---",    // 5A
    "XXXXX---",
    "----X---",
    "----X---",
    "---X----",
    "---X----",
    "--X-----",
    "--X-----",
    "-X------",
    "-X------",
    "X-------",
    "X-------",
    "XXXXX---",
    "XXXXX---",
    "--------",
    "--------",


    "XXXXX---",    // 5B
    "XXXXX---",
    "XX------",
    "XX------",
    "XX------",
    "XX------",
    "XX------",
    "XX------",
    "XX------",
    "XX------",
    "XX------",
    "XX------",
    "XXXXX---",
    "XXXXX---",
    "--------",
    "--------",


    "--------",    // 5C
    "--------",
    "--------",
    "--------",
    "X-------",
    "X-------",
    "-X------",
    "-X------",
    "--X-----",
    "--X-----",
    "---X----",
    "---X----",
    "----X---",
    "----X---",
    "--------",
    "--------",


    "XXXXX---",    // 5D
    "XXXXX---",
    "---XX---",
    "---XX---",
    "---XX---",
    "---XX---",
    "---XX---",
    "---XX---",
    "---XX---",
    "---XX---",
    "---XX---",
    "---XX---",
    "XXXXX---",
    "XXXXX---",
    "--------",
    "--------",


    "--------",    // 5E
    "--------",
    "--------",
    "--------",
    "--X-----",
    "--X-----",
    "-XXX----",
    "-XXX----",
    "X-X-X---",
    "X-X-X---",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",


    "--------",    // 5F
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "XXXXX---",
    "XXXXX---",
    "--------",
    "--------",


    "--------",    // 60
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",


    "--------",    // 61
    "--------",
    "--------",
    "--------",
    "XXX-----",
    "XXX-----",
    "---X----",
    "---X----",
    "-XXX----",
    "-XXX----",
    "X--X----",
    "X--X----",
    "-XX-X---",
    "-XX-X---",
    "--------",
    "--------",


    "X-------",    // 62
    "X-------",
    "X-------",
    "X-------",
    "XXX-----",
    "XXX-----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "XXXX----",
    "XXXX----",
    "--------",
    "--------",


    "--------",    // 63
    "--------",
    "--------",
    "--------",
    "-XXX----",
    "-XXX----",
    "X---X---",
    "X---X---",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "-XXXX---",
    "-XXXX---",
    "--------",
    "--------",


    "----X---",    // 64
    "----X---",
    "----X---",
    "----X---",
    "-XXXX---",
    "-XXXX---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "-XXXX---",
    "-XXXX---",
    "--------",
    "--------",


    "--------",    // 65
    "--------",
    "--------",
    "--------",
    "-XXX----",
    "-XXX----",
    "X---X---",
    "X---X---",
    "XXXXX---",
    "XXXXX---",
    "X-------",
    "X-------",
    "-XXXX---",
    "-XXXX---",
    "--------",
    "--------",


    "--XX----",    // 66
    "--XX----",
    "-X--X---",
    "-X--X---",
    "-X------",
    "-X------",
    "XXX-----",
    "XXX-----",
    "-X------",
    "-X------",
    "-X------",
    "-X------",
    "-X------",
    "-X------",
    "--------",
    "--------",


    "--------",    // 67
    "--------",
    "--------",
    "--------",
    "-XXXX---",
    "-XXXX---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "-XXXX---",
    "-XXXX---",
    "----X---",
    "----X---",
    "XXXX----",
    "XXXX----",


    "X-------",    // 68
    "X-------",
    "X-------",
    "X-------",
    "X-XX----",
    "X-XX----",
    "XX--X---",
    "XX--X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "--X-----",    // 69
    "--X-----",
    "--------",
    "--------",
    "-XX-----",
    "-XX-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "---X----",    // 6A
    "---X----",
    "--------",
    "--------",
    "---X----",
    "---X----",
    "---X----",
    "---X----",
    "---X----",
    "---X----",
    "---X----",
    "---X----",
    "X--X----",
    "X--X----",
    "-XX-----",
    "-XX-----",


    "X-------",    // 6B
    "X-------",
    "X-------",
    "X-------",
    "X---X---",
    "X---X---",
    "X--X----",
    "X--X----",
    "X-X-----",
    "X-X-----",
    "XX-X----",
    "XX-X----",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "-XX-----",    // 6C
    "-XX-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "--------",    // 6D
    "--------",
    "--------",
    "--------",
    "XX-X----",
    "XX-XX---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "--------",
    "--------",


    "--------",    // 6E
    "--------",
    "--------",
    "--------",
    "X-XX----",
    "X-XX----",
    "-X--X---",
    "-X--X---",
    "-X--X---",
    "-X--X---",
    "-X--X---",
    "-X--X---",
    "-X--X---",
    "-X--X---",
    "--------",
    "--------",


    "--------",    // 6F
    "--------",
    "--------",
    "--------",
    "-XXX----",
    "-XXX----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "--------",    // 70
    "--------",
    "--------",
    "--------",
    "XXXX----",
    "XXXX----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "XXXX----",
    "XXXX----",
    "X-------",
    "X-------",
    "X-------",
    "X-------",


    "--------",    // 71
    "--------",
    "--------",
    "--------",
    "-XXXX---",
    "-XXXX---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "-XXXX---",
    "-XXXX---",
    "----X---",
    "----X---",
    "----X---",
    "----X---",


    "--------",    // 72
    "--------",
    "--------",
    "--------",
    "X-XX----",
    "X-XX----",
    "XX--X---",
    "XX--X---",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "--------",
    "--------",


    "--------",    // 73
    "--------",
    "--------",
    "--------",
    "-XXXX---",
    "-XXXX---",
    "X-------",
    "X-------",
    "-XXX----",
    "-XXX----",
    "----X---",
    "----X---",
    "XXXX----",
    "XXXX----",
    "--------",
    "--------",


    "--------",    // 74
    "--------",
    "-X------",
    "-X------",
    "XXXX----",
    "XXXX----",
    "-X------",
    "-X------",
    "-X------",
    "-X------",
    "-X------",
    "-X------",
    "--XX----",
    "--XX----",
    "--------",
    "--------",


    "--------",    // 75
    "--------",
    "--------",
    "--------",
    "X--X----",
    "X--X----",
    "X--X----",
    "X--X----",
    "X--X----",
    "X--X----",
    "X--X----",
    "X--X----",
    "-XX-X---",
    "-XX-X---",
    "--------",
    "--------",


    "--------",    // 76
    "--------",
    "--------",
    "--------",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "-X-X----",
    "-X-X----",
    "--X-----",
    "--X-----",
    "--------",
    "--------",


    "--------",    // 77
    "--------",
    "--------",
    "--------",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "-X-X----",
    "-X-X----",
    "--------",
    "--------",


    "--------",    // 78
    "--------",
    "--------",
    "--------",
    "X---X---",
    "X---X---",
    "-X-X----",
    "-X-X----",
    "--X-----",
    "--X-----",
    "-X-X----",
    "-X-X----",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "--------",    // 79
    "--------",
    "--------",
    "--------",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "-X-X----",
    "-X-X----",
    "--X-----",
    "--X-----",
    "-X------",
    "-X------",
    "X-------",
    "X-------",


    "--------",    // 7A
    "--------",
    "--------",
    "--------",
    "XXXXX---",
    "XXXXX---",
    "---X----",
    "---X----",
    "--X-----",
    "--X-----",
    "-X------",
    "-X------",
    "XXXXX---",
    "XXXXX---",
    "--------",
    "--------",


    "--------",    // 7B
    "--XX----",
    "--XX----",
    "-X------",
    "-X------",
    "-X------",
    "-X------",
    "X-------",
    "X-------",
    "-X------",
    "-X------",
    "-X------",
    "-X------",
    "--XX----",
    "--XX----",
    "--------",


    "--------",    // 7C
    "--------",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--------",
    "--------",


    "--------",    // 7D
    "-XX-----",
    "-XX-----",
    "---X----",
    "---X----",
    "---X----",
    "---X----",
    "----X---",
    "----X---",
    "---X----",
    "---X----",
    "---X----",
    "---X----",
    "-XX-----",
    "-XX-----",
    "--------",


    "--------",    // 7E
    "--------",
    "-X------",
    "-X------",
    "X-X-X---",
    "X-X-X---",
    "---X----",
    "---X----",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",


    "XXXXXXX-",    // 7F
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-",


    "-XXX----",    // 80
    "-XXX----",
    "X---X---",
    "X---X---",
    "X-X-X---",
    "X-X-X---",
    "X-XXX---",
    "X-XXX---",
    "X-XX----",
    "X-XX----",
    "X-------",
    "X-------",
    "-XXXX---",
    "-XXXX---",
    "--------",
    "--------",


    "--X-----",    // 81
    "--X-----",
    "-X-X----",
    "-X-X----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "XXXXX---",
    "XXXXX---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "XXXX----",    // 82
    "XXXX----",
    "-X--X---",
    "-X--X---",
    "-X--X---",
    "-X--X---",
    "-XXX----",
    "-XXX----",
    "-X--X---",
    "-X--X---",
    "-X--X---",
    "-X--X---",
    "XXXX----",
    "XXXX----",
    "--------",
    "--------",


    "-XXX----",    // 83
    "-XXX----",
    "X---X---",
    "X---X---",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X---X---",
    "X---X---",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "XXXX----",    // 84
    "XXXX----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "XXXX----",
    "XXXX----",
    "--------",
    "--------",


    "XXXXX---",    // 85
    "XXXXX---",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "XXXX----",
    "XXXX----",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "XXXXX---",
    "XXXXX---",
    "--------",
    "--------",


    "XXXXX---",    // 86
    "XXXXX---",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "XXXX----",
    "XXXX----",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "--------",
    "--------",


    "-XXXX---",    // 87
    "-XXXX---",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X--XX---",
    "X--XX---",
    "X---X---",
    "X---X---",
    "-XXXX---",
    "-XXXX---",
    "--------",
    "--------",


    "X---X---",    // 88
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "XXXXX---",
    "XXXXX---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "-XXX----",    // 89
    "-XXX----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "----X---",    // 8A
    "----X---",
    "----X---",
    "----X---",
    "----X---",
    "----X---",
    "----X---",
    "----X---",
    "----X---",
    "----X---",
    "X---X---",
    "X---X---",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "X---X---",    // 8B
    "X---X---",
    "X--X----",
    "X--X----",
    "X-X-----",
    "X-X-----",
    "XX------",
    "XX------",
    "X-X-----",
    "X-X-----",
    "X--X----",
    "X--X----",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "X-------",    // 8C
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "XXXXX---",
    "XXXXX---",
    "--------",
    "--------",


    "X---X---",    // 8D
    "X---X---",
    "XX-XX---",
    "XX-XX---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "X---X---",    // 8E
    "X---X---",
    "X---X---",
    "X---X---",
    "XX--X---",
    "XX--X---",
    "X-X-X---",
    "X-X-X---",
    "X--XX---",
    "X--XX---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "-XXX----",    // 8F
    "-XXX----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "XXXX----",    // 90
    "XXXX----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "XXXX----",
    "XXXX----",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "--------",
    "--------",


    "-XXX----",    // 91
    "-XXX----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X-X-X---",
    "X-X-X---",
    "X--X----",
    "X--X----",
    "-XX-X---",
    "-XX-X---",
    "--------",
    "--------",


    "XXXX----",    // 92
    "XXXX----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "XXXX----",
    "XXXX----",
    "X-X-----",
    "X-X-----",
    "X--X----",
    "X--X----",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "-XXX----",    // 93
    "-XXX----",
    "X---X---",
    "X---X---",
    "X-------",
    "X-------",
    "-XXX----",
    "-XXX----",
    "----X---",
    "----X---",
    "X---X---",
    "X---X---",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "XXXXX---",    // 94
    "XXXXX---",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--------",
    "--------",


    "X---X---",    // 95
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "X---X---",    // 96
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "-X-X----",
    "-X-X----",
    "--X-----",
    "--X-----",
    "--------",
    "--------",


    "X---X---",    // 97
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "XX-XX---",
    "XX-XX---",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "X---X---",    // 98
    "X---X---",
    "X---X---",
    "X---X---",
    "-X-X----",
    "-X-X----",
    "--X-----",
    "--X-----",
    "-X-X----",
    "-X-X----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "X---X---",    // 99
    "X---X---",
    "X---X---",
    "X---X---",
    "-X-X----",
    "-X-X----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--------",
    "--------",


    "XXXXX---",    // 9A
    "XXXXX---",
    "----X---",
    "----X---",
    "---X----",
    "---X----",
    "--X-----",
    "--X-----",
    "-X------",
    "-X------",
    "X-------",
    "X-------",
    "XXXXX---",
    "XXXXX---",
    "--------",
    "--------",


    "XXXXX---",    // 9B
    "XXXXX---",
    "XX------",
    "XX------",
    "XX------",
    "XX------",
    "XX------",
    "XX------",
    "XX------",
    "XX------",
    "XX------",
    "XX------",
    "XXXXX---",
    "XXXXX---",
    "--------",
    "--------",


    "--------",    // 9C
    "--------",
    "--------",
    "--------",
    "X-------",
    "X-------",
    "-X------",
    "-X------",
    "--X-----",
    "--X-----",
    "---X----",
    "---X----",
    "----X---",
    "----X---",
    "--------",
    "--------",


    "XXXXX---",    // 9D
    "XXXXX---",
    "---XX---",
    "---XX---",
    "---XX---",
    "---XX---",
    "---XX---",
    "---XX---",
    "---XX---",
    "---XX---",
    "---XX---",
    "---XX---",
    "XXXXX---",
    "XXXXX---",
    "--------",
    "--------",


    "--------",    // 9E
    "--------",
    "--------",
    "--------",
    "--X-----",
    "--X-----",
    "-XXX----",
    "-XXX----",
    "X-X-X---",
    "X-X-X---",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",


    "--------",    // 9F
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "XXXXX---",
    "XXXXX---",
    "--------",
    "--------",


    "--------",    // A0
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",


    "---X----",    // A1
    "---X----",
    "---X----",
    "---X----",
    "---X----",
    "---X----",
    "---X----",
    "---X----",
    "--------",
    "--------",
    "--------",
    "--------",
    "---X----",
    "---X----",
    "--------",
    "--------",


    "--X-X---",    // A2
    "--X-X---",
    "--X-X---",
    "--X-X---",
    "--X-X---",
    "--X-X---",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",


    "-X-X----",    // A3
    "-X-X----",
    "-X-X----",
    "-X-X----",
    "XXXXX---",
    "XXXXX---",
    "-X-X----",
    "-X-X----",
    "XXXXX---",
    "XXXXX---",
    "-X-X----",
    "-X-X----",
    "-X-X----",
    "-X-X----",
    "--------",
    "--------",


    "--X-----",    // A4
    "--X-----",
    "-XXXX---",
    "-XXXX---",
    "X-X-----",
    "X-X-----",
    "-XXX----",
    "-XXX----",
    "--X-X---",
    "--X-X---",
    "XXXX----",
    "XXXX----",
    "--X-----",
    "--X-----",
    "--------",
    "--------",


    "XX------",    // A5
    "XX------",
    "XX--X---",
    "XX--X---",
    "---X----",
    "---X----",
    "--X-----",
    "--X-----",
    "-X------",
    "-X------",
    "X--XX---",
    "X--XX---",
    "---XX---",
    "---XX---",
    "--------",
    "--------",


    "-X------",    // A6
    "-X------",
    "X-X-----",
    "X-X-----",
    "X-X-----",
    "X-X-----",
    "-X------",
    "-X------",
    "X-X-X---",
    "X-X-X---",
    "X--X----",
    "X--X----",
    "-XX-X---",
    "-XX-X---",
    "--------",
    "--------",


    "---X----",    // A7
    "---X----",
    "---X----",
    "---X----",
    "---X----",
    "---X----",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",


    "--X-----",    // A8
    "--X-----",
    "-X------",
    "-X------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "-X------",
    "-X------",
    "--X-----",
    "--X-----",
    "--------",
    "--------",


    "--X-----",    // A9
    "--X-----",
    "---X----",
    "---X----",
    "----X---",
    "----X---",
    "----X---",
    "----X---",
    "----X---",
    "----X---",
    "---X----",
    "---X----",
    "--X-----",
    "--X-----",
    "--------",
    "--------",


    "--X-----",    // AA
    "--X-----",
    "X-X-X---",
    "X-X-X---",
    "-XXX----",
    "-XXX----",
    "--X-----",
    "--X-----",
    "-XXX----",
    "-XXX----",
    "X-X-X---",
    "X-X-X---",
    "--X-----",
    "--X-----",
    "--------",
    "--------",


    "--------",    // AB
    "--------",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "XXXXX---",
    "XXXXX---",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--------",
    "--------",
    "--------",
    "--------",


    "--------",    // AC
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "---X----",
    "---X----",
    "---X----",
    "---X----",
    "--X-----",
    "--X-----",
    "--------",
    "--------",


    "--------",    // AD
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "-XXXXX--",
    "-XXXXX--",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",


    "--------",    // AE
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--X-----",
    "--X-----",
    "--------",
    "--------",


    "--------",    // AF
    "--------",
    "----X---",
    "----X---",
    "---X----",
    "---X----",
    "--X-----",
    "--X-----",
    "-X------",
    "-X------",
    "X-------",
    "X-------",
    "--------",
    "--------",
    "--------",
    "--------",


    "-XXX----",    // B0
    "-XXX----",
    "X---X---",
    "X---X---",
    "X--XX---",
    "X--XX---",
    "X-X-X---",
    "X-X-X---",
    "XX--X---",
    "XX--X---",
    "X---X---",
    "X---X---",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "--X-----",    // B1
    "--X-----",
    "-XX-----",
    "-XX-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "-XXX----",    // B2
    "-XXX----",
    "X---X---",
    "X---X---",
    "----X---",
    "----X---",
    "--XX----",
    "--XX----",
    "-X------",
    "-X------",
    "X-------",
    "X-------",
    "XXXXX---",
    "XXXXX---",
    "--------",
    "--------",


    "XXXXX---",    // B3
    "XXXXX---",
    "----X---",
    "----X---",
    "---X----",
    "---X----",
    "--XX----",
    "--XX----",
    "----X---",
    "----X---",
    "X---X---",
    "X---X---",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "---X----",    // B4
    "---X----",
    "--XX----",
    "--XX----",
    "-X-X----",
    "-X-X----",
    "X--X----",
    "X--X----",
    "XXXXX---",
    "XXXXX---",
    "---X----",
    "---X----",
    "---X----",
    "---X----",
    "--------",
    "--------",


    "XXXXX---",    // B5
    "XXXXX---",
    "X-------",
    "X-------",
    "XXXX----",
    "XXXX----",
    "----X---",
    "----X---",
    "----X---",
    "----X---",
    "X---X---",
    "X---X---",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "--XXX---",    // B6
    "--XXX---",
    "-X------",
    "-X------",
    "X-------",
    "X-------",
    "XXXX----",
    "XXXX----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "XXXXX---",    // B7
    "XXXXX---",
    "----X---",
    "----X---",
    "---X----",
    "---X----",
    "--X-----",
    "--X-----",
    "-X------",
    "-X------",
    "-X------",
    "-X------",
    "-X------",
    "-X------",
    "--------",
    "--------",


    "-XXX----",    // B8
    "-XXX----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "-XXX----",
    "-XXX----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "-XXX----",    // B9
    "-XXX----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "-XXXX---",
    "-XXXX---",
    "----X---",
    "----X---",
    "---X----",
    "---X----",
    "XXX-----",
    "XXX-----",
    "--------",
    "--------",


    "--------",    // BA
    "--------",
    "--------",
    "--------",
    "--X-----",
    "--X-----",
    "--------",
    "--------",
    "--X-----",
    "--X-----",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",


    "--------",    // BB
    "--------",
    "--------",
    "--------",
    "---X----",
    "---X----",
    "--------",
    "--------",
    "---X----",
    "---X----",
    "---X----",
    "---X----",
    "--X-----",
    "--X-----",
    "--------",
    "--------",


    "---X----",    // BC
    "---X----",
    "--X-----",
    "--X-----",
    "-X------",
    "-X------",
    "X-------",
    "X-------",
    "-X------",
    "-X------",
    "--X-----",
    "--X-----",
    "---X----",
    "---X----",
    "--------",
    "--------",


    "--------",    // BD
    "--------",
    "--------",
    "--------",
    "XXXXX---",
    "XXXXX---",
    "--------",
    "--------",
    "XXXXX---",
    "XXXXX---",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",


    "--X-----",    // BE
    "--X-----",
    "---X----",
    "---X----",
    "----X---",
    "----X---",
    "-----X--",
    "-----X--",
    "----X---",
    "----X---",
    "---X----",
    "---X----",
    "--X-----",
    "--X-----",
    "--------",
    "--------",


    "-XXX----",    // BF
    "-XXX----",
    "X---X---",
    "X---X---",
    "---X----",
    "---X----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--------",
    "--------",
    "--X-----",
    "--X-----",
    "--------",
    "--------",


    "-XXX----",    // C0
    "-XXX----",
    "X---X---",
    "X---X---",
    "X-X-X---",
    "X-X-X---",
    "X-XXX---",
    "X-XXX---",
    "X-XX----",
    "X-XX----",
    "X-------",
    "X-------",
    "-XXXX---",
    "-XXXX---",
    "--------",
    "--------",


    "--X-----",    // C1
    "--X-----",
    "-X-X----",
    "-X-X----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "XXXXX---",
    "XXXXX---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "XXXX----",    // C2
    "XXXX----",
    "-X--X---",
    "-X--X---",
    "-X--X---",
    "-X--X---",
    "-XXX----",
    "-XXX----",
    "-X--X---",
    "-X--X---",
    "-X--X---",
    "-X--X---",
    "XXXX----",
    "XXXX----",
    "--------",
    "--------",


    "-XXX----",    // C3
    "-XXX----",
    "X---X---",
    "X---X---",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X---X---",
    "X---X---",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "XXXX----",    // C4
    "XXXX----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "XXXX----",
    "XXXX----",
    "--------",
    "--------",


    "XXXXX---",    // C5
    "XXXXX---",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "XXXX----",
    "XXXX----",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "XXXXX---",
    "XXXXX---",
    "--------",
    "--------",


    "XXXXX---",    // C6
    "XXXXX---",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "XXXX----",
    "XXXX----",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "--------",
    "--------",


    "-XXXX---",    // C7
    "-XXXX---",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X--XX---",
    "X--XX---",
    "X---X---",
    "X---X---",
    "-XXXX---",
    "-XXXX---",
    "--------",
    "--------",


    "X---X---",    // C8
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "XXXXX---",
    "XXXXX---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "-XXX----",    // C9
    "-XXX----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "----X---",    // CA
    "----X---",
    "----X---",
    "----X---",
    "----X---",
    "----X---",
    "----X---",
    "----X---",
    "----X---",
    "----X---",
    "X---X---",
    "X---X---",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "X---X---",    // CB
    "X---X---",
    "X--X----",
    "X--X----",
    "X-X-----",
    "X-X-----",
    "XX------",
    "XX------",
    "X-X-----",
    "X-X-----",
    "X--X----",
    "X--X----",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "X-------",    // CC
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "XXXXX---",
    "XXXXX---",
    "--------",
    "--------",


    "X---X---",    // CD
    "X---X---",
    "XX-XX---",
    "XX-XX---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "X---X---",    // CE
    "X---X---",
    "X---X---",
    "X---X---",
    "XX--X---",
    "XX--X---",
    "X-X-X---",
    "X-X-X---",
    "X--XX---",
    "X--XX---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "-XXX----",    // CF
    "-XXX----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "XXXX----",    // D0
    "XXXX----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "XXXX----",
    "XXXX----",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "--------",
    "--------",


    "-XXX----",    // D1
    "-XXX----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X-X-X---",
    "X-X-X---",
    "X--X----",
    "X--X----",
    "-XX-X---",
    "-XX-X---",
    "--------",
    "--------",


    "XXXX----",    // D2
    "XXXX----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "XXXX----",
    "XXXX----",
    "X-X-----",
    "X-X-----",
    "X--X----",
    "X--X----",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "-XXX----",    // D3
    "-XXX----",
    "X---X---",
    "X---X---",
    "X-------",
    "X-------",
    "-XXX----",
    "-XXX----",
    "----X---",
    "----X---",
    "X---X---",
    "X---X---",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "XXXXX---",    // D4
    "XXXXX---",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--------",
    "--------",


    "X---X---",    // D5
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "X---X---",    // D6
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "-X-X----",
    "-X-X----",
    "--X-----",
    "--X-----",
    "--------",
    "--------",


    "X---X---",    // D7
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "XX-XX---",
    "XX-XX---",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "X---X---",    // D8
    "X---X---",
    "X---X---",
    "X---X---",
    "-X-X----",
    "-X-X----",
    "--X-----",
    "--X-----",
    "-X-X----",
    "-X-X----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "X---X---",    // D9
    "X---X---",
    "X---X---",
    "X---X---",
    "-X-X----",
    "-X-X----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--------",
    "--------",


    "XXXXX---",    // DA
    "XXXXX---",
    "----X---",
    "----X---",
    "---X----",
    "---X----",
    "--X-----",
    "--X-----",
    "-X------",
    "-X------",
    "X-------",
    "X-------",
    "XXXXX---",
    "XXXXX---",
    "--------",
    "--------",


    "XXXXX---",    // DB
    "XXXXX---",
    "XX------",
    "XX------",
    "XX------",
    "XX------",
    "XX------",
    "XX------",
    "XX------",
    "XX------",
    "XX------",
    "XX------",
    "XXXXX---",
    "XXXXX---",
    "--------",
    "--------",


    "--------",    // DC
    "--------",
    "X-------",
    "X-------",
    "-X------",
    "-X------",
    "--X-----",
    "--X-----",
    "---X----",
    "---X----",
    "----X---",
    "----X---",
    "--------",
    "--------",
    "--------",
    "--------",


    "XXXXX---",    // DD
    "XXXXX---",
    "---XX---",
    "---XX---",
    "---XX---",
    "---XX---",
    "---XX---",
    "---XX---",
    "---XX---",
    "---XX---",
    "---XX---",
    "---XX---",
    "XXXXX---",
    "XXXXX---",
    "--------",
    "--------",


    "--------",    // DE
    "--------",
    "--------",
    "--------",
    "--X-----",
    "--X-----",
    "-XXX----",
    "-XXX----",
    "X-X-X---",
    "X-X-X---",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",


    "--------",    // DF
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "XXXXX---",
    "XXXXX---",
    "--------",
    "--------",


    "--------",    // E0
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",


    "--------",    // E1
    "--------",
    "--------",
    "--------",
    "XXX-----",
    "XXX-----",
    "---X----",
    "---X----",
    "-XXX----",
    "-XXX----",
    "X--X----",
    "X--X----",
    "-XX-X---",
    "-XX-X---",
    "--------",
    "--------",


    "X-------",    // E2
    "X-------",
    "X-------",
    "X-------",
    "XXXX----",
    "XXXX----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "XXXX----",
    "XXXX----",
    "--------",
    "--------",


    "--------",    // E3
    "--------",
    "--------",
    "--------",
    "-XXX----",
    "-XXX----",
    "X---X---",
    "X---X---",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "-XXXX---",
    "-XXXX---",
    "--------",
    "--------",


    "----X---",    // E4
    "----X---",
    "----X---",
    "----X---",
    "-XXXX---",
    "-XXXX---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "-XXXX---",
    "-XXXX---",
    "--------",
    "--------",


    "--------",    // E5
    "--------",
    "--------",
    "--------",
    "-XXX----",
    "-XXX----",
    "X---X---",
    "X---X---",
    "XXXXX---",
    "XXXXX---",
    "X-------",
    "X-------",
    "-XXXX---",
    "-XXXX---",
    "--------",
    "--------",


    "--XX----",    // E6
    "--XX----",
    "-X--X---",
    "-X--X---",
    "-X------",
    "-X------",
    "XXX-----",
    "XXX-----",
    "-X------",
    "-X------",
    "-X------",
    "-X------",
    "-X------",
    "-X------",
    "--------",
    "--------",


    "--------",    // E7
    "--------",
    "--------",
    "--------",
    "-XXXX---",
    "-XXXX---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "-XXXX---",
    "-XXXX---",
    "----X---",
    "----X---",
    "XXXX----",
    "XXXX----",


    "X-------",    // E8
    "X-------",
    "X-------",
    "X-------",
    "X-XX----",
    "X-XX----",
    "XX--X---",
    "XX--X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "--X-----",    // E9
    "--X-----",
    "--------",
    "--------",
    "-XX-----",
    "-XX-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "---X----",    // EA
    "---X----",
    "--------",
    "--------",
    "---X----",
    "---X----",
    "---X----",
    "---X----",
    "---X----",
    "---X----",
    "---X----",
    "---X----",
    "X--X----",
    "X--X----",
    "-XX-----",
    "-XX-----",


    "X-------",    // EB
    "X-------",
    "X-------",
    "X-------",
    "X---X---",
    "X---X---",
    "X--X----",
    "X--X----",
    "X-X-----",
    "X-X-----",
    "XX-X----",
    "XX-X----",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "-XX-----",    // EC
    "-XX-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "--------",    // ED
    "--------",
    "--------",
    "--------",
    "XX-X----",
    "XX-XX---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "--------",
    "--------",


    "--------",    // EE
    "--------",
    "--------",
    "--------",
    "X-XX----",
    "X-XX----",
    "-X--X---",
    "-X--X---",
    "-X--X---",
    "-X--X---",
    "-X--X---",
    "-X--X---",
    "-X--X---",
    "-X--X---",
    "--------",
    "--------",


    "--------",    // EF
    "--------",
    "--------",
    "--------",
    "-XXX----",
    "-XXX----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "-XXX----",
    "-XXX----",
    "--------",
    "--------",


    "--------",    // F0
    "--------",
    "--------",
    "--------",
    "XXXX----",
    "XXXX----",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "XXXX----",
    "XXXX----",
    "X-------",
    "X-------",
    "X-------",
    "X-------",


    "--------",    // F1
    "--------",
    "--------",
    "--------",
    "-XXXX---",
    "-XXXX---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "-XXXX---",
    "-XXXX---",
    "----X---",
    "----X---",
    "----X---",
    "----X---",


    "--------",    // F2
    "--------",
    "--------",
    "--------",
    "X-XX----",
    "X-XX----",
    "XX--X---",
    "XX--X---",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "X-------",
    "--------",
    "--------",


    "--------",    // F3
    "--------",
    "--------",
    "--------",
    "-XXXX---",
    "-XXXX---",
    "X-------",
    "X-------",
    "-XXX----",
    "-XXX----",
    "----X---",
    "----X---",
    "XXXX----",
    "XXXX----",
    "--------",
    "--------",


    "--------",    // F4
    "--------",
    "-X------",
    "-X------",
    "XXXX----",
    "XXXX----",
    "-X------",
    "-X------",
    "-X------",
    "-X------",
    "-X------",
    "-X------",
    "--XX----",
    "--XX----",
    "--------",
    "--------",


    "--------",    // F5
    "--------",
    "--------",
    "--------",
    "X--X----",
    "X--X----",
    "X--X----",
    "X--X----",
    "X--X----",
    "X--X----",
    "X--X----",
    "X--X----",
    "-XX-X---",
    "-XX-X---",
    "--------",
    "--------",


    "--------",    // F6
    "--------",
    "--------",
    "--------",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "-X-X----",
    "-X-X----",
    "--X-----",
    "--X-----",
    "--------",
    "--------",


    "--------",    // F7
    "--------",
    "--------",
    "--------",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "X-X-X---",
    "-X-X----",
    "-X-X----",
    "--------",
    "--------",


    "--------",    // F8
    "--------",
    "--------",
    "--------",
    "X---X---",
    "X---X---",
    "-X-X----",
    "-X-X----",
    "--X-----",
    "--X-----",
    "-X-X----",
    "-X-X----",
    "X---X---",
    "X---X---",
    "--------",
    "--------",


    "--------",    // F9
    "--------",
    "--------",
    "--------",
    "X---X---",
    "X---X---",
    "X---X---",
    "X---X---",
    "-X-X----",
    "-X-X----",
    "--X-----",
    "--X-----",
    "-X------",
    "-X------",
    "X-------",
    "X-------",


    "--------",    // FA
    "--------",
    "--------",
    "--------",
    "XXXXX---",
    "XXXXX---",
    "---X----",
    "---X----",
    "--X-----",
    "--X-----",
    "-X------",
    "-X------",
    "XXXXX---",
    "XXXXX---",
    "--------",
    "--------",


    "--------",    // FB
    "--XX----",
    "--XX----",
    "-X------",
    "-X------",
    "-X------",
    "-X------",
    "X-------",
    "X-------",
    "-X------",
    "-X------",
    "-X------",
    "-X------",
    "--XX----",
    "--XX----",
    "--------",


    "--------",    // FC
    "--------",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--X-----",
    "--------",
    "--------",


    "--------",    // FD
    "-XX-----",
    "-XX-----",
    "---X----",
    "---X----",
    "---X----",
    "---X----",
    "----X---",
    "----X---",
    "---X----",
    "---X----",
    "---X----",
    "---X----",
    "-XX-----",
    "-XX-----",
    "--------",


    "--------",    // FE
    "--------",
    "-X------",
    "-X------",
    "X-X-X---",
    "X-X-X---",
    "---X----",
    "---X----",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",


    "XXXXXXX-",    // FF
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-",
    "XXXXXXX-"


} ;

