/*****************************************************************************

    File: "xpm_80column_chars.cpp"

    Copyright (C) 2003,2019 Bruce Ward

    This file is part of ApplePi, an Apple2 emulator.
    (Apple2 is a trademark of Apple, Inc.)

    "ApplePi" is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    "ApplePi" is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You may obtain a copy of the GNU General Public License by writing to:

    The Free Software Foundation, Inc.
    51 Franklin Street, Fifth Floor
    Boston, MA 02110-1335 USA

    Or simply visit: https://www.gnu.org/licenses/gpl-3.0.html

*****************************************************************************/


const char* xpm_80ColChars[] =
{
    "8 4096 2 1",
    "X c #ffffff",
    "- c #000000",

    "X---XXXX",    // 00
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-X-X-XXX",
    "XXXXXXXX",
    "-X---XXX",
    "XXXXXXXX",
    "-X--XXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "X----XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XX-XXXXX",    // 01
    "XXXXXXXX",
    "X-X-XXXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-----XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "----XXXX",    // 02
    "XXXXXXXX",
    "X-XX-XXX",
    "XXXXXXXX",
    "X-XX-XXX",
    "XXXXXXXX",
    "X---XXXX",
    "XXXXXXXX",
    "X-XX-XXX",
    "XXXXXXXX",
    "X-XX-XXX",
    "XXXXXXXX",
    "----XXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X---XXXX",    // 03
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "----XXXX",    // 04
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "----XXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-----XXX",    // 05
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "----XXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "-----XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-----XXX",    // 06
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "----XXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X----XXX",    // 07
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "-XX--XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "X----XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-XXX-XXX",    // 08
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-----XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X---XXXX",    // 09
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXXX-XXX",    // 0A
    "XXXXXXXX",
    "XXXX-XXX",
    "XXXXXXXX",
    "XXXX-XXX",
    "XXXXXXXX",
    "XXXX-XXX",
    "XXXXXXXX",
    "XXXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-XXX-XXX",    // 0B
    "XXXXXXXX",
    "-XX-XXXX",
    "XXXXXXXX",
    "-X-XXXXX",
    "XXXXXXXX",
    "--XXXXXX",
    "XXXXXXXX",
    "-X-XXXXX",
    "XXXXXXXX",
    "-XX-XXXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-XXXXXXX",    // 0C
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "-----XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-XXX-XXX",    // 0D
    "XXXXXXXX",
    "--X--XXX",
    "XXXXXXXX",
    "-X-X-XXX",
    "XXXXXXXX",
    "-X-X-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-XXX-XXX",    // 0E
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "--XX-XXX",
    "XXXXXXXX",
    "-X-X-XXX",
    "XXXXXXXX",
    "-XX--XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X---XXXX",    // 0F
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "----XXXX",    // 10
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "----XXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X---XXXX",    // 11
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-X-X-XXX",
    "XXXXXXXX",
    "-XX-XXXX",
    "XXXXXXXX",
    "X--X-XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "----XXXX",    // 12
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "----XXXX",
    "XXXXXXXX",
    "-X-XXXXX",
    "XXXXXXXX",
    "-XX-XXXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X---XXXX",    // 13
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XXXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-----XXX",    // 14
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-XXX-XXX",    // 15
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-XXX-XXX",    // 16
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "X-X-XXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-XXX-XXX",    // 17
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-X-X-XXX",
    "XXXXXXXX",
    "-X-X-XXX",
    "XXXXXXXX",
    "--X--XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-XXX-XXX",    // 18
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "X-X-XXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "X-X-XXXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-XXX-XXX",    // 19
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "X-X-XXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-----XXX",    // 1A
    "XXXXXXXX",
    "XXXX-XXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "X-XXXXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "-----XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-----XXX",    // 1B
    "XXXXXXXX",
    "--XXXXXX",
    "XXXXXXXX",
    "--XXXXXX",
    "XXXXXXXX",
    "--XXXXXX",
    "XXXXXXXX",
    "--XXXXXX",
    "XXXXXXXX",
    "--XXXXXX",
    "XXXXXXXX",
    "-----XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXXXXXXX",    // 1C
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "X-XXXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XXXX-XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-----XXX",    // 1D
    "XXXXXXXX",
    "XXX--XXX",
    "XXXXXXXX",
    "XXX--XXX",
    "XXXXXXXX",
    "XXX--XXX",
    "XXXXXXXX",
    "XXX--XXX",
    "XXXXXXXX",
    "XXX--XXX",
    "XXXXXXXX",
    "-----XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXXXXXXX",    // 1E
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "X---XXXX",
    "XXXXXXXX",
    "-X-X-XXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",


    "XXXXXXXX",    // 1F
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "-----XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXXXXXXX",    // 20
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXX-XXXX",    // 21
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XX-X-XXX",    // 22
    "XXXXXXXX",
    "XX-X-XXX",
    "XXXXXXXX",
    "XX-X-XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X-X-XXXX",    // 23
    "XXXXXXXX",
    "X-X-XXXX",
    "XXXXXXXX",
    "-----XXX",
    "XXXXXXXX",
    "X-X-XXXX",
    "XXXXXXXX",
    "-----XXX",
    "XXXXXXXX",
    "X-X-XXXX",
    "XXXXXXXX",
    "X-X-XXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XX-XXXXX",    // 24
    "XXXXXXXX",
    "X----XXX",
    "XXXXXXXX",
    "-X-XXXXX",
    "XXXXXXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XX-X-XXX",
    "XXXXXXXX",
    "----XXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "--XXXXXX",    // 25
    "XXXXXXXX",
    "--XX-XXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "X-XXXXXX",
    "XXXXXXXX",
    "-XX--XXX",
    "XXXXXXXX",
    "XXX--XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X-XXXXXX",    // 26
    "XXXXXXXX",
    "-X-XXXXX",
    "XXXXXXXX",
    "-X-XXXXX",
    "XXXXXXXX",
    "X-XXXXXX",
    "XXXXXXXX",
    "-X-X-XXX",
    "XXXXXXXX",
    "-XX-XXXX",
    "XXXXXXXX",
    "X--X-XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXX-XXXX",    // 27
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XX-XXXXX",    // 28
    "XXXXXXXX",
    "X-XXXXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "X-XXXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XX-XXXXX",    // 29
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XXXX-XXX",
    "XXXXXXXX",
    "XXXX-XXX",
    "XXXXXXXX",
    "XXXX-XXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XX-XXXXX",    // 2A
    "XXXXXXXX",
    "-X-X-XXX",
    "XXXXXXXX",
    "X---XXXX",
    "XXXXXXXX",
    "X---XXXX",
    "XXXXXXXX",
    "-X-X-XXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXXXXXXX",    // 2B
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "-----XXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXXXXXXX",    // 2C
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXXXXXXX",    // 2D
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "X-----XX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXXXXXXX",    // 2E
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXXXXXXX",    // 2F
    "XXXXXXXX",
    "XXXX-XXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "X-XXXXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X---XXXX",    // 30
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XX--XXX",
    "XXXXXXXX",
    "-X-X-XXX",
    "XXXXXXXX",
    "--XX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XX-XXXXX",    // 31
    "XXXXXXXX",
    "X--XXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X---XXXX",    // 32
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "XXXX-XXX",
    "XXXXXXXX",
    "XX--XXXX",
    "XXXXXXXX",
    "X-XXXXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "-----XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-----XXX",    // 33
    "XXXXXXXX",
    "XXXX-XXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XX--XXXX",
    "XXXXXXXX",
    "XXXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXX-XXXX",    // 34
    "XXXXXXXX",
    "XX--XXXX",
    "XXXXXXXX",
    "X-X-XXXX",
    "XXXXXXXX",
    "-XX-XXXX",
    "XXXXXXXX",
    "-----XXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-----XXX",    // 35
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "----XXXX",
    "XXXXXXXX",
    "XXXX-XXX",
    "XXXXXXXX",
    "XXXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XX---XXX",    // 36
    "XXXXXXXX",
    "X-XXXXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "----XXXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-----XXX",    // 37
    "XXXXXXXX",
    "XXXX-XXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "X-XXXXXX",
    "XXXXXXXX",
    "X-XXXXXX",
    "XXXXXXXX",
    "X-XXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X---XXXX",    // 38
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "X---XXXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "X---XXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X---XXXX",    // 39
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "X----XXX",
    "XXXXXXXX",
    "XXXX-XXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "---XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXXXXXXX",    // 3A
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXXXXXXX",    // 3B
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXX-XXXX",    // 3C
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "X-XXXXXX",
    "XXXXXXXX",
    "-XXXXXXX",
    "XXXXXXXX",
    "X-XXXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XXXXXXXX",    // 3D
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "-----XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "-----XXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "XX-XXXXX",    // 3E
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XXXX-XXX",
    "XXXXXXXX",
    "XXXXX-XX",
    "XXXXXXXX",
    "XXXX-XXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "X---XXXX",    // 3F
    "XXXXXXXX",
    "-XXX-XXX",
    "XXXXXXXX",
    "XXX-XXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XX-XXXXX",
    "XXXXXXXX",
    "XXXXXXXX",
    "XXXXXXXX",


    "-XXX----",    // 40
    "--------",
    "X---X---",
    "--------",
    "X-X-X---",
    "--------",
    "X-XXX---",
    "--------",
    "X-XX----",
    "--------",
    "X-------",
    "--------",
    "-XXXX---",
    "--------",
    "--------",
    "--------",


    "--X-----",    // 41
    "--------",
    "-X-X----",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "XXXXX---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "XXXX----",    // 42
    "--------",
    "-X--X---",
    "--------",
    "-X--X---",
    "--------",
    "-XXX----",
    "--------",
    "-X--X---",
    "--------",
    "-X--X---",
    "--------",
    "XXXX----",
    "--------",
    "--------",
    "--------",


    "-XXX----",    // 43
    "--------",
    "X---X---",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X---X---",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "XXXX----",    // 44
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "XXXX----",
    "--------",
    "--------",
    "--------",


    "XXXXX---",    // 45
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "XXXX----",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "XXXXX---",
    "--------",
    "--------",
    "--------",


    "XXXXX---",    // 46
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "XXXX----",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "--------",
    "--------",


    "-XXXX---",    // 47
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X--XX---",
    "--------",
    "X---X---",
    "--------",
    "-XXXX---",
    "--------",
    "--------",
    "--------",


    "X---X---",    // 48
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "XXXXX---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "-XXX----",    // 49
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "----X---",    // 4A
    "--------",
    "----X---",
    "--------",
    "----X---",
    "--------",
    "----X---",
    "--------",
    "----X---",
    "--------",
    "X---X---",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "X---X---",    // 4B
    "--------",
    "X--X----",
    "--------",
    "X-X-----",
    "--------",
    "XX------",
    "--------",
    "X-X-----",
    "--------",
    "X--X----",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "X-------",    // 4C
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "XXXXX---",
    "--------",
    "--------",
    "--------",


    "X---X---",    // 4D
    "--------",
    "XX-XX---",
    "--------",
    "X-X-X---",
    "--------",
    "X-X-X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "X---X---",    // 4E
    "--------",
    "X---X---",
    "--------",
    "XX--X---",
    "--------",
    "X-X-X---",
    "--------",
    "X--XX---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "-XXX----",    // 4F
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "XXXX----",    // 50
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "XXXX----",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "--------",
    "--------",


    "-XXX----",    // 51
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X-X-X---",
    "--------",
    "X--X----",
    "--------",
    "-XX-X---",
    "--------",
    "--------",
    "--------",


    "XXXX----",    // 52
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "XXXX----",
    "--------",
    "X-X-----",
    "--------",
    "X--X----",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "-XXX----",    // 53
    "--------",
    "X---X---",
    "--------",
    "X-------",
    "--------",
    "-XXX----",
    "--------",
    "----X---",
    "--------",
    "X---X---",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "XXXXX---",    // 54
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",


    "X---X---",    // 55
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "X---X---",    // 56
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "-X-X----",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",


    "X---X---",    // 57
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X-X-X---",
    "--------",
    "X-X-X---",
    "--------",
    "XX-XX---",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "X---X---",    // 58
    "--------",
    "X---X---",
    "--------",
    "-X-X----",
    "--------",
    "--X-----",
    "--------",
    "-X-X----",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "X---X---",    // 59
    "--------",
    "X---X---",
    "--------",
    "-X-X----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",


    "XXXXX---",    // 5A
    "--------",
    "----X---",
    "--------",
    "---X----",
    "--------",
    "--X-----",
    "--------",
    "-X------",
    "--------",
    "X-------",
    "--------",
    "XXXXX---",
    "--------",
    "--------",
    "--------",


    "XXXXX---",    // 5B
    "--------",
    "XX------",
    "--------",
    "XX------",
    "--------",
    "XX------",
    "--------",
    "XX------",
    "--------",
    "XX------",
    "--------",
    "XXXXX---",
    "--------",
    "--------",
    "--------",


    "--------",    // 5C
    "--------",
    "--------",
    "--------",
    "X-------",
    "--------",
    "-X------",
    "--------",
    "--X-----",
    "--------",
    "---X----",
    "--------",
    "----X---",
    "--------",
    "--------",
    "--------",


    "XXXXX---",    // 5D
    "--------",
    "---XX---",
    "--------",
    "---XX---",
    "--------",
    "---XX---",
    "--------",
    "---XX---",
    "--------",
    "---XX---",
    "--------",
    "XXXXX---",
    "--------",
    "--------",
    "--------",


    "--------",    // 5E
    "--------",
    "--------",
    "--------",
    "--X-----",
    "--------",
    "-XXX----",
    "--------",
    "X-X-X---",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",


    "--------",    // 5F
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "XXXXX---",
    "--------",
    "--------",
    "--------",


    "--------",    // 60
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",


    "--------",    // 61
    "--------",
    "--------",
    "--------",
    "XXX-----",
    "--------",
    "---X----",
    "--------",
    "-XXX----",
    "--------",
    "X--X----",
    "--------",
    "-XX-X---",
    "--------",
    "--------",
    "--------",


    "X-------",    // 62
    "--------",
    "X-------",
    "--------",
    "XXX-----",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "XXXX----",
    "--------",
    "--------",
    "--------",


    "--------",    // 63
    "--------",
    "--------",
    "--------",
    "-XXX----",
    "--------",
    "X---X---",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "-XXXX---",
    "--------",
    "--------",
    "--------",


    "----X---",    // 64
    "--------",
    "----X---",
    "--------",
    "-XXXX---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "-XXXX---",
    "--------",
    "--------",
    "--------",


    "--------",    // 65
    "--------",
    "--------",
    "--------",
    "-XXX----",
    "--------",
    "X---X---",
    "--------",
    "XXXXX---",
    "--------",
    "X-------",
    "--------",
    "-XXXX---",
    "--------",
    "--------",
    "--------",


    "--XX----",    // 66
    "--------",
    "-X--X---",
    "--------",
    "-X------",
    "--------",
    "XXX-----",
    "--------",
    "-X------",
    "--------",
    "-X------",
    "--------",
    "-X------",
    "--------",
    "--------",
    "--------",


    "--------",    // 67
    "--------",
    "--------",
    "--------",
    "-XXXX---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "-XXXX---",
    "--------",
    "----X---",
    "--------",
    "XXXX----",
    "--------",


    "X-------",    // 68
    "--------",
    "X-------",
    "--------",
    "X-XX----",
    "--------",
    "XX--X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "--X-----",    // 69
    "--------",
    "--------",
    "--------",
    "-XX-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "---X----",    // 6A
    "--------",
    "--------",
    "--------",
    "---X----",
    "--------",
    "---X----",
    "--------",
    "---X----",
    "--------",
    "---X----",
    "--------",
    "X--X----",
    "--------",
    "-XX-----",
    "--------",


    "X-------",    // 6B
    "--------",
    "X-------",
    "--------",
    "X---X---",
    "--------",
    "X--X----",
    "--------",
    "X-X-----",
    "--------",
    "XX-X----",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "-XX-----",    // 6C
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "--------",    // 6D
    "--------",
    "--------",
    "--------",
    "XX-X----",
    "--------",
    "X-X-X---",
    "--------",
    "X-X-X---",
    "--------",
    "X-X-X---",
    "--------",
    "X-X-X---",
    "--------",
    "--------",
    "--------",


    "--------",    // 6E
    "--------",
    "--------",
    "--------",
    "X-XX----",
    "--------",
    "-X--X---",
    "--------",
    "-X--X---",
    "--------",
    "-X--X---",
    "--------",
    "-X--X---",
    "--------",
    "--------",
    "--------",


    "--------",    // 6F
    "--------",
    "--------",
    "--------",
    "-XXX----",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "--------",    // 70
    "--------",
    "--------",
    "--------",
    "XXXX----",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "XXXX----",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",


    "--------",    // 71
    "--------",
    "--------",
    "--------",
    "-XXXX---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "-XXXX---",
    "--------",
    "----X---",
    "--------",
    "----X---",
    "--------",


    "--------",    // 72
    "--------",
    "--------",
    "--------",
    "X-XX----",
    "--------",
    "XX--X---",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "--------",
    "--------",


    "--------",    // 73
    "--------",
    "--------",
    "--------",
    "-XXXX---",
    "--------",
    "X-------",
    "--------",
    "-XXX----",
    "--------",
    "----X---",
    "--------",
    "XXXX----",
    "--------",
    "--------",
    "--------",


    "--------",    // 74
    "--------",
    "-X------",
    "--------",
    "XXXX----",
    "--------",
    "-X------",
    "--------",
    "-X------",
    "--------",
    "-X------",
    "--------",
    "--XX----",
    "--------",
    "--------",
    "--------",


    "--------",    // 75
    "--------",
    "--------",
    "--------",
    "X--X----",
    "--------",
    "X--X----",
    "--------",
    "X--X----",
    "--------",
    "X--X----",
    "--------",
    "-XX-X---",
    "--------",
    "--------",
    "--------",


    "--------",    // 76
    "--------",
    "--------",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "-X-X----",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",


    "--------",    // 77
    "--------",
    "--------",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X-X-X---",
    "--------",
    "X-X-X---",
    "--------",
    "-X-X----",
    "--------",
    "--------",
    "--------",


    "--------",    // 78
    "--------",
    "--------",
    "--------",
    "X---X---",
    "--------",
    "-X-X----",
    "--------",
    "--X-----",
    "--------",
    "-X-X----",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "--------",    // 79
    "--------",
    "--------",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "-X-X----",
    "--------",
    "--X-----",
    "--------",
    "-X------",
    "--------",
    "X-------",
    "--------",


    "--------",    // 7A
    "--------",
    "--------",
    "--------",
    "XXXXX---",
    "--------",
    "---X----",
    "--------",
    "--X-----",
    "--------",
    "-X------",
    "--------",
    "XXXXX---",
    "--------",
    "--------",
    "--------",


    "--------",    // 7B
    "--------",
    "--XX----",
    "--------",
    "-X------",
    "--------",
    "-X------",
    "--------",
    "X-------",
    "--------",
    "-X------",
    "--------",
    "-X------",
    "--------",
    "--XX----",
    "--------",


    "--------",    // 7C
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",


    "--------",    // 7D
    "--------",
    "-XX-----",
    "--------",
    "---X----",
    "--------",
    "---X----",
    "--------",
    "----X---",
    "--------",
    "---X----",
    "--------",
    "---X----",
    "--------",
    "-XX-----",
    "--------",


    "--------",    // 7E
    "--------",
    "-X------",
    "--------",
    "X-X-X---",
    "--------",
    "---X----",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",


    "XXXXXXX-",    // 7F
    "--------",
    "XXXXXXX-",
    "--------",
    "XXXXXXX-",
    "--------",
    "XXXXXXX-",
    "--------",
    "XXXXXXX-",
    "--------",
    "XXXXXXX-",
    "--------",
    "XXXXXXX-",
    "--------",
    "XXXXXXX-",
    "--------",


    "-XXX----",    // 80
    "--------",
    "X---X---",
    "--------",
    "X-X-X---",
    "--------",
    "X-XXX---",
    "--------",
    "X-XX----",
    "--------",
    "X-------",
    "--------",
    "-XXXX---",
    "--------",
    "--------",
    "--------",


    "--X-----",    // 81
    "--------",
    "-X-X----",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "XXXXX---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "XXXX----",    // 82
    "--------",
    "-X--X---",
    "--------",
    "-X--X---",
    "--------",
    "-XXX----",
    "--------",
    "-X--X---",
    "--------",
    "-X--X---",
    "--------",
    "XXXX----",
    "--------",
    "--------",
    "--------",


    "-XXX----",    // 83
    "--------",
    "X---X---",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X---X---",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "XXXX----",    // 84
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "XXXX----",
    "--------",
    "--------",
    "--------",


    "XXXXX---",    // 85
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "XXXX----",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "XXXXX---",
    "--------",
    "--------",
    "--------",


    "XXXXX---",    // 86
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "XXXX----",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "--------",
    "--------",


    "-XXXX---",    // 87
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X--XX---",
    "--------",
    "X---X---",
    "--------",
    "-XXXX---",
    "--------",
    "--------",
    "--------",


    "X---X---",    // 88
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "XXXXX---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "-XXX----",    // 89
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "----X---",    // 8A
    "--------",
    "----X---",
    "--------",
    "----X---",
    "--------",
    "----X---",
    "--------",
    "----X---",
    "--------",
    "X---X---",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "X---X---",    // 8B
    "--------",
    "X--X----",
    "--------",
    "X-X-----",
    "--------",
    "XX------",
    "--------",
    "X-X-----",
    "--------",
    "X--X----",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "X-------",    // 8C
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "XXXXX---",
    "--------",
    "--------",
    "--------",


    "X---X---",    // 8D
    "--------",
    "XX-XX---",
    "--------",
    "X-X-X---",
    "--------",
    "X-X-X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "X---X---",    // 8E
    "--------",
    "X---X---",
    "--------",
    "XX--X---",
    "--------",
    "X-X-X---",
    "--------",
    "X--XX---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "-XXX----",    // 8F
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "XXXX----",    // 90
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "XXXX----",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "--------",
    "--------",


    "-XXX----",    // 91
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X-X-X---",
    "--------",
    "X--X----",
    "--------",
    "-XX-X---",
    "--------",
    "--------",
    "--------",


    "XXXX----",    // 92
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "XXXX----",
    "--------",
    "X-X-----",
    "--------",
    "X--X----",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "-XXX----",    // 93
    "--------",
    "X---X---",
    "--------",
    "X-------",
    "--------",
    "-XXX----",
    "--------",
    "----X---",
    "--------",
    "X---X---",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "XXXXX---",    // 94
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",


    "X---X---",    // 95
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "X---X---",    // 96
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "-X-X----",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",


    "X---X---",    // 97
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X-X-X---",
    "--------",
    "X-X-X---",
    "--------",
    "XX-XX---",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "X---X---",    // 98
    "--------",
    "X---X---",
    "--------",
    "-X-X----",
    "--------",
    "--X-----",
    "--------",
    "-X-X----",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "X---X---",    // 99
    "--------",
    "X---X---",
    "--------",
    "-X-X----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",


    "XXXXX---",    // 9A
    "--------",
    "----X---",
    "--------",
    "---X----",
    "--------",
    "--X-----",
    "--------",
    "-X------",
    "--------",
    "X-------",
    "--------",
    "XXXXX---",
    "--------",
    "--------",
    "--------",


    "XXXXX---",    // 9B
    "--------",
    "XX------",
    "--------",
    "XX------",
    "--------",
    "XX------",
    "--------",
    "XX------",
    "--------",
    "XX------",
    "--------",
    "XXXXX---",
    "--------",
    "--------",
    "--------",


    "--------",    // 9C
    "--------",
    "--------",
    "--------",
    "X-------",
    "--------",
    "-X------",
    "--------",
    "--X-----",
    "--------",
    "---X----",
    "--------",
    "----X---",
    "--------",
    "--------",
    "--------",


    "XXXXX---",    // 9D
    "--------",
    "---XX---",
    "--------",
    "---XX---",
    "--------",
    "---XX---",
    "--------",
    "---XX---",
    "--------",
    "---XX---",
    "--------",
    "XXXXX---",
    "--------",
    "--------",
    "--------",


    "--------",    // 9E
    "--------",
    "--------",
    "--------",
    "--X-----",
    "--------",
    "-XXX----",
    "--------",
    "X-X-X---",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",


    "--------",    // 9F
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "XXXXX---",
    "--------",
    "--------",
    "--------",


    "--------",    // A0
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",


    "---X----",    // A1
    "--------",
    "---X----",
    "--------",
    "---X----",
    "--------",
    "---X----",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "---X----",
    "--------",
    "--------",
    "--------",


    "--X-X---",    // A2
    "--------",
    "--X-X---",
    "--------",
    "--X-X---",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",


    "-X-X----",    // A3
    "--------",
    "-X-X----",
    "--------",
    "XXXXX---",
    "--------",
    "-X-X----",
    "--------",
    "XXXXX---",
    "--------",
    "-X-X----",
    "--------",
    "-X-X----",
    "--------",
    "--------",
    "--------",


    "--X-----",    // A4
    "--------",
    "-XXXX---",
    "--------",
    "X-X-----",
    "--------",
    "-XXX----",
    "--------",
    "--X-X---",
    "--------",
    "XXXX----",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",


    "XX------",    // A5
    "--------",
    "XX--X---",
    "--------",
    "---X----",
    "--------",
    "--X-----",
    "--------",
    "-X------",
    "--------",
    "X--XX---",
    "--------",
    "---XX---",
    "--------",
    "--------",
    "--------",


    "-X------",    // A6
    "--------",
    "X-X-----",
    "--------",
    "X-X-----",
    "--------",
    "-X------",
    "--------",
    "X-X-X---",
    "--------",
    "X--X----",
    "--------",
    "-XX-X---",
    "--------",
    "--------",
    "--------",


    "---X----",    // A7
    "--------",
    "---X----",
    "--------",
    "---X----",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",


    "--X-----",    // A8
    "--------",
    "-X------",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "-X------",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",


    "--X-----",    // A9
    "--------",
    "---X----",
    "--------",
    "----X---",
    "--------",
    "----X---",
    "--------",
    "----X---",
    "--------",
    "---X----",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",


    "--X-----",    // AA
    "--------",
    "X-X-X---",
    "--------",
    "-XXX----",
    "--------",
    "-XXX----",
    "--------",
    "X-X-X---",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",


    "--------",    // AB
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "XXXXX---",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",


    "--------",    // AC
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "---X----",
    "--------",
    "---X----",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",


    "--------",    // AD
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "-XXXXX--",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",


    "--------",    // AE
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",


    "--------",    // AF
    "--------",
    "----X---",
    "--------",
    "---X----",
    "--------",
    "--X-----",
    "--------",
    "-X------",
    "--------",
    "X-------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",


    "-XXX----",    // B0
    "--------",
    "X---X---",
    "--------",
    "X--XX---",
    "--------",
    "X-X-X---",
    "--------",
    "XX--X---",
    "--------",
    "X---X---",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "--X-----",    // B1
    "--------",
    "-XX-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "-XXX----",    // B2
    "--------",
    "X---X---",
    "--------",
    "----X---",
    "--------",
    "--XX----",
    "--------",
    "-X------",
    "--------",
    "X-------",
    "--------",
    "XXXXX---",
    "--------",
    "--------",
    "--------",


    "XXXXX---",    // B3
    "--------",
    "----X---",
    "--------",
    "---X----",
    "--------",
    "--XX----",
    "--------",
    "----X---",
    "--------",
    "X---X---",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "---X----",    // B4
    "--------",
    "--XX----",
    "--------",
    "-X-X----",
    "--------",
    "X--X----",
    "--------",
    "XXXXX---",
    "--------",
    "---X----",
    "--------",
    "---X----",
    "--------",
    "--------",
    "--------",


    "XXXXX---",    // B5
    "--------",
    "X-------",
    "--------",
    "XXXX----",
    "--------",
    "----X---",
    "--------",
    "----X---",
    "--------",
    "X---X---",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "--XXX---",    // B6
    "--------",
    "-X------",
    "--------",
    "X-------",
    "--------",
    "XXXX----",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "XXXXX---",    // B7
    "--------",
    "----X---",
    "--------",
    "---X----",
    "--------",
    "--X-----",
    "--------",
    "-X------",
    "--------",
    "-X------",
    "--------",
    "-X------",
    "--------",
    "--------",
    "--------",


    "-XXX----",    // B8
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "-XXX----",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "-XXX----",    // B9
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "-XXXX---",
    "--------",
    "----X---",
    "--------",
    "---X----",
    "--------",
    "XXX-----",
    "--------",
    "--------",
    "--------",


    "--------",    // BA
    "--------",
    "--------",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",


    "--------",    // BB
    "--------",
    "--------",
    "--------",
    "---X----",
    "--------",
    "--------",
    "--------",
    "---X----",
    "--------",
    "---X----",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",


    "---X----",    // BC
    "--------",
    "--X-----",
    "--------",
    "-X------",
    "--------",
    "X-------",
    "--------",
    "-X------",
    "--------",
    "--X-----",
    "--------",
    "---X----",
    "--------",
    "--------",
    "--------",


    "--------",    // BD
    "--------",
    "--------",
    "--------",
    "XXXXX---",
    "--------",
    "--------",
    "--------",
    "XXXXX---",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",


    "--X-----",    // BE
    "--------",
    "---X----",
    "--------",
    "----X---",
    "--------",
    "-----X--",
    "--------",
    "----X---",
    "--------",
    "---X----",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",


    "-XXX----",    // BF
    "--------",
    "X---X---",
    "--------",
    "---X----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",


    "-XXX----",    // C0
    "--------",
    "X---X---",
    "--------",
    "X-X-X---",
    "--------",
    "X-XXX---",
    "--------",
    "X-XX----",
    "--------",
    "X-------",
    "--------",
    "-XXXX---",
    "--------",
    "--------",
    "--------",


    "--X-----",    // C1
    "--------",
    "-X-X----",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "XXXXX---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "XXXX----",    // C2
    "--------",
    "-X--X---",
    "--------",
    "-X--X---",
    "--------",
    "-XXX----",
    "--------",
    "-X--X---",
    "--------",
    "-X--X---",
    "--------",
    "XXXX----",
    "--------",
    "--------",
    "--------",


    "-XXX----",    // C3
    "--------",
    "X---X---",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X---X---",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "XXXX----",    // C4
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "XXXX----",
    "--------",
    "--------",
    "--------",


    "XXXXX---",    // C5
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "XXXX----",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "XXXXX---",
    "--------",
    "--------",
    "--------",


    "XXXXX---",    // C6
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "XXXX----",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "--------",
    "--------",


    "-XXXX---",    // C7
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X--XX---",
    "--------",
    "X---X---",
    "--------",
    "-XXXX---",
    "--------",
    "--------",
    "--------",


    "X---X---",    // C8
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "XXXXX---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "-XXX----",    // C9
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "----X---",    // CA
    "--------",
    "----X---",
    "--------",
    "----X---",
    "--------",
    "----X---",
    "--------",
    "----X---",
    "--------",
    "X---X---",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "X---X---",    // CB
    "--------",
    "X--X----",
    "--------",
    "X-X-----",
    "--------",
    "XX------",
    "--------",
    "X-X-----",
    "--------",
    "X--X----",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "X-------",    // CC
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "XXXXX---",
    "--------",
    "--------",
    "--------",


    "X---X---",    // CD
    "--------",
    "XX-XX---",
    "--------",
    "X-X-X---",
    "--------",
    "X-X-X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "X---X---",    // CE
    "--------",
    "X---X---",
    "--------",
    "XX--X---",
    "--------",
    "X-X-X---",
    "--------",
    "X--XX---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "-XXX----",    // CF
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "XXXX----",    // D0
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "XXXX----",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "--------",
    "--------",


    "-XXX----",    // D1
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X-X-X---",
    "--------",
    "X--X----",
    "--------",
    "-XX-X---",
    "--------",
    "--------",
    "--------",


    "XXXX----",    // D2
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "XXXX----",
    "--------",
    "X-X-----",
    "--------",
    "X--X----",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "-XXX----",    // D3
    "--------",
    "X---X---",
    "--------",
    "X-------",
    "--------",
    "-XXX----",
    "--------",
    "----X---",
    "--------",
    "X---X---",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "XXXXX---",    // D4
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",


    "X---X---",    // D5
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "X---X---",    // D6
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "-X-X----",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",


    "X---X---",    // D7
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X-X-X---",
    "--------",
    "X-X-X---",
    "--------",
    "XX-XX---",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "X---X---",    // D8
    "--------",
    "X---X---",
    "--------",
    "-X-X----",
    "--------",
    "--X-----",
    "--------",
    "-X-X----",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "X---X---",    // D9
    "--------",
    "X---X---",
    "--------",
    "-X-X----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",


    "XXXXX---",    // DA
    "--------",
    "----X---",
    "--------",
    "---X----",
    "--------",
    "--X-----",
    "--------",
    "-X------",
    "--------",
    "X-------",
    "--------",
    "XXXXX---",
    "--------",
    "--------",
    "--------",


    "XXXXX---",    // DB
    "--------",
    "XX------",
    "--------",
    "XX------",
    "--------",
    "XX------",
    "--------",
    "XX------",
    "--------",
    "XX------",
    "--------",
    "XXXXX---",
    "--------",
    "--------",
    "--------",


    "--------",    // DC
    "--------",
    "X-------",
    "--------",
    "-X------",
    "--------",
    "--X-----",
    "--------",
    "---X----",
    "--------",
    "----X---",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",


    "XXXXX---",    // DD
    "--------",
    "---XX---",
    "--------",
    "---XX---",
    "--------",
    "---XX---",
    "--------",
    "---XX---",
    "--------",
    "---XX---",
    "--------",
    "XXXXX---",
    "--------",
    "--------",
    "--------",


    "--------",    // DE
    "--------",
    "--------",
    "--------",
    "--X-----",
    "--------",
    "-XXX----",
    "--------",
    "X-X-X---",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",


    "--------",    // DF
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "XXXXX---",
    "--------",
    "--------",
    "--------",


    "--------",    // E0
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",


    "--------",    // E1
    "--------",
    "--------",
    "--------",
    "XXX-----",
    "--------",
    "---X----",
    "--------",
    "-XXX----",
    "--------",
    "X--X----",
    "--------",
    "-XX-X---",
    "--------",
    "--------",
    "--------",


    "X-------",    // E2
    "--------",
    "X-------",
    "--------",
    "XXXX----",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "XXXX----",
    "--------",
    "--------",
    "--------",


    "--------",    // E3
    "--------",
    "--------",
    "--------",
    "-XXX----",
    "--------",
    "X---X---",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "-XXXX---",
    "--------",
    "--------",
    "--------",


    "----X---",    // E4
    "--------",
    "----X---",
    "--------",
    "-XXXX---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "-XXXX---",
    "--------",
    "--------",
    "--------",


    "--------",    // E5
    "--------",
    "--------",
    "--------",
    "-XXX----",
    "--------",
    "X---X---",
    "--------",
    "XXXXX---",
    "--------",
    "X-------",
    "--------",
    "-XXXX---",
    "--------",
    "--------",
    "--------",


    "--XX----",    // E6
    "--------",
    "-X--X---",
    "--------",
    "-X------",
    "--------",
    "XXX-----",
    "--------",
    "-X------",
    "--------",
    "-X------",
    "--------",
    "-X------",
    "--------",
    "--------",
    "--------",


    "--------",    // E7
    "--------",
    "--------",
    "--------",
    "-XXXX---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "-XXXX---",
    "--------",
    "----X---",
    "--------",
    "XXXX----",
    "--------",


    "X-------",    // E8
    "--------",
    "X-------",
    "--------",
    "X-XX----",
    "--------",
    "XX--X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "--X-----",    // E9
    "--------",
    "--------",
    "--------",
    "-XX-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "---X----",    // EA
    "--------",
    "--------",
    "--------",
    "---X----",
    "--------",
    "---X----",
    "--------",
    "---X----",
    "--------",
    "---X----",
    "--------",
    "X--X----",
    "--------",
    "-XX-----",
    "--------",


    "X-------",    // EB
    "--------",
    "X-------",
    "--------",
    "X---X---",
    "--------",
    "X--X----",
    "--------",
    "X-X-----",
    "--------",
    "XX-X----",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "-XX-----",    // EC
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "--------",    // ED
    "--------",
    "--------",
    "--------",
    "XX-X----",
    "--------",
    "X-X-X---",
    "--------",
    "X-X-X---",
    "--------",
    "X-X-X---",
    "--------",
    "X-X-X---",
    "--------",
    "--------",
    "--------",


    "--------",    // EE
    "--------",
    "--------",
    "--------",
    "X-XX----",
    "--------",
    "-X--X---",
    "--------",
    "-X--X---",
    "--------",
    "-X--X---",
    "--------",
    "-X--X---",
    "--------",
    "--------",
    "--------",


    "--------",    // EF
    "--------",
    "--------",
    "--------",
    "-XXX----",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "-XXX----",
    "--------",
    "--------",
    "--------",


    "--------",    // F0
    "--------",
    "--------",
    "--------",
    "XXXX----",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "XXXX----",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",


    "--------",    // F1
    "--------",
    "--------",
    "--------",
    "-XXXX---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "-XXXX---",
    "--------",
    "----X---",
    "--------",
    "----X---",
    "--------",


    "--------",    // F2
    "--------",
    "--------",
    "--------",
    "X-XX----",
    "--------",
    "XX--X---",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "X-------",
    "--------",
    "--------",
    "--------",


    "--------",    // F3
    "--------",
    "--------",
    "--------",
    "-XXXX---",
    "--------",
    "X-------",
    "--------",
    "-XXX----",
    "--------",
    "----X---",
    "--------",
    "XXXX----",
    "--------",
    "--------",
    "--------",


    "--------",    // F4
    "--------",
    "-X------",
    "--------",
    "XXXX----",
    "--------",
    "-X------",
    "--------",
    "-X------",
    "--------",
    "-X------",
    "--------",
    "--XX----",
    "--------",
    "--------",
    "--------",


    "--------",    // F5
    "--------",
    "--------",
    "--------",
    "X--X----",
    "--------",
    "X--X----",
    "--------",
    "X--X----",
    "--------",
    "X--X----",
    "--------",
    "-XX-X---",
    "--------",
    "--------",
    "--------",


    "--------",    // F6
    "--------",
    "--------",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "-X-X----",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",


    "--------",    // F7
    "--------",
    "--------",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "X-X-X---",
    "--------",
    "X-X-X---",
    "--------",
    "-X-X----",
    "--------",
    "--------",
    "--------",


    "--------",    // F8
    "--------",
    "--------",
    "--------",
    "X---X---",
    "--------",
    "-X-X----",
    "--------",
    "--X-----",
    "--------",
    "-X-X----",
    "--------",
    "X---X---",
    "--------",
    "--------",
    "--------",


    "--------",    // F9
    "--------",
    "--------",
    "--------",
    "X---X---",
    "--------",
    "X---X---",
    "--------",
    "-X-X----",
    "--------",
    "--X-----",
    "--------",
    "-X------",
    "--------",
    "X-------",
    "--------",


    "--------",    // FA
    "--------",
    "--------",
    "--------",
    "XXXXX---",
    "--------",
    "---X----",
    "--------",
    "--X-----",
    "--------",
    "-X------",
    "--------",
    "XXXXX---",
    "--------",
    "--------",
    "--------",


    "--------",    // FB
    "--------",
    "--XX----",
    "--------",
    "-X------",
    "--------",
    "-X------",
    "--------",
    "X-------",
    "--------",
    "-X------",
    "--------",
    "-X------",
    "--------",
    "--XX----",
    "--------",


    "--------",    // FC
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--X-----",
    "--------",
    "--------",
    "--------",


    "--------",    // FD
    "--------",
    "-XX-----",
    "--------",
    "---X----",
    "--------",
    "---X----",
    "--------",
    "----X---",
    "--------",
    "---X----",
    "--------",
    "---X----",
    "--------",
    "-XX-----",
    "--------",


    "--------",    // FE
    "--------",
    "-X------",
    "--------",
    "X-X-X---",
    "--------",
    "---X----",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",
    "--------",


    "XXXXXXX-",    // FF
    "--------",
    "XXXXXXX-",
    "--------",
    "XXXXXXX-",
    "--------",
    "XXXXXXX-",
    "--------",
    "XXXXXXX-",
    "--------",
    "XXXXXXX-",
    "--------",
    "XXXXXXX-",
    "--------",
    "XXXXXXX-",
    "--------",


} ;

